openapi: 3.1.0
info:
  title: Stockfriend Orchestrator API
  version: 1.0.0

servers:
  - url: https://fictional-space-spoon-x556qx6qp4xp26pq7-10000.app.github.dev

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: []

paths:
  /healthz:
    get:
      summary: Health check
      responses:
        "200":
          description: OK

  /sf/run:
    post:
      summary: Execute Stockfriend operation plan
      operationId: runOrchestrator
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plan:
                  type: array
                  description: Ordered list of operations for the orchestrator.
                  items:
                    type: object
                    properties:
                      op:
                        type: string
                        description: Operation name (e.g. getRegulatory, ensureToken, getQuotes).
                    required:
                      - op
              required:
                - plan
      responses:
        "200":
          description: Successful execution
          content:
            application/json:
              schema:
                type: object
